sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vaibhavpuri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vaibhavpuri/docker-react npm run test